use univer;
DROP TABLE IF EXISTS PROGRESS;
DROP TABLE IF EXISTS STUDENT;
DROP TABLE IF EXISTS GROUPS;
DROP TABLE IF EXISTS SUBJECT;
DROP TABLE IF EXISTS TEACHER;
DROP TABLE IF EXISTS PULPIT;
DROP TABLE IF EXISTS PROFESSION;
DROP TABLE IF EXISTS FACULTY;

CREATE TABLE FACULTY (
    FACULTY CHAR(10) PRIMARY KEY,
    FACULTY_NAME NVARCHAR(50) DEFAULT '???'
);

CREATE TABLE PROFESSION (
    PROFESSION CHAR(20) PRIMARY KEY,
    FACULTY CHAR(10) FOREIGN KEY REFERENCES FACULTY(FACULTY),
    PROFESSION_NAME NVARCHAR(100),
    QUALIFICATION NVARCHAR(50)
);

CREATE TABLE PULPIT (
    PULPIT CHAR(20) PRIMARY KEY,
    PULPIT_NAME NVARCHAR(100),
    FACULTY CHAR(10) FOREIGN KEY REFERENCES FACULTY(FACULTY)
);

CREATE TABLE TEACHER (
    TEACHER CHAR(10) PRIMARY KEY,
    TEACHER_NAME NVARCHAR(100),
    TEACHER_SURNAME NVARCHAR(100),
    TEACHER_PATRONYMIC NVARCHAR(100),
    GENDER CHAR(1) CHECK (GENDER IN ('ì', 'æ')),
    START_DATE DATE NOT NULL,
    WORK_TIME DECIMAL(10, 2) NOT NULL,
    PULPIT CHAR(20) FOREIGN KEY REFERENCES PULPIT(PULPIT)
);

CREATE TABLE SUBJECT (
    SUBJECT CHAR(10) PRIMARY KEY,
    SUBJECT_NAME NVARCHAR(100) UNIQUE,
    TEACHER CHAR(10) FOREIGN KEY REFERENCES TEACHER(TEACHER)
);

CREATE TABLE GROUPS (
    IDGROUP INT IDENTITY(1,1) PRIMARY KEY,
    FACULTY CHAR(10) FOREIGN KEY REFERENCES FACULTY(FACULTY),
    PROFESSION CHAR(20) FOREIGN KEY REFERENCES PROFESSION(PROFESSION),
    YEAR_FIRST SMALLINT CHECK (YEAR_FIRST <= 9999)
);

CREATE TABLE STUDENT (
    IDSTUDENT INT IDENTITY(1,1) PRIMARY KEY,
    IDGROUP INT FOREIGN KEY REFERENCES GROUPS(IDGROUP),
    STUDENT_NAME NVARCHAR(100),
    STUDENT_SURNAME NVARCHAR(100),
    STUDENT_PATRONYMIC NVARCHAR(100),
    BDAY DATE
);

CREATE TABLE PROGRESS (
    SUBJECT CHAR(10) FOREIGN KEY REFERENCES SUBJECT(SUBJECT),
    IDSTUDENT INT FOREIGN KEY REFERENCES STUDENT(IDSTUDENT),
    PDATE DATE,
    ESTIMATION INT CHECK (ESTIMATION BETWEEN 1 AND 10),
    PRIMARY KEY (SUBJECT, IDSTUDENT, PDATE)
);