// Mocks generated by Mockito 5.4.4 from annotations
// in hotel_app/test/unit_tests/lab13_unit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:firebase_auth/firebase_auth.dart' as _i4;
import 'package:hotel_app/favorite.dart' as _i7;
import 'package:hotel_app/hotel.dart' as _i6;
import 'package:hotel_app/services/auth_service.dart' as _i2;
import 'package:hotel_app/services/firestore_service.dart' as _i5;
import 'package:hotel_app/user.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i2.AuthService {
  @override
  _i3.Stream<_i4.User?> get authStateChanges => (super.noSuchMethod(
        Invocation.getter(#authStateChanges),
        returnValue: _i3.Stream<_i4.User?>.empty(),
        returnValueForMissingStub: _i3.Stream<_i4.User?>.empty(),
      ) as _i3.Stream<_i4.User?>);

  @override
  _i3.Future<_i4.UserCredential?> registerWithEmailPassword(
    String? email,
    String? password,
    String? name,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #registerWithEmailPassword,
          [
            email,
            password,
            name,
          ],
        ),
        returnValue: _i3.Future<_i4.UserCredential?>.value(),
        returnValueForMissingStub: _i3.Future<_i4.UserCredential?>.value(),
      ) as _i3.Future<_i4.UserCredential?>);

  @override
  _i3.Future<_i4.UserCredential?> signInWithEmailPassword(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithEmailPassword,
          [
            email,
            password,
          ],
        ),
        returnValue: _i3.Future<_i4.UserCredential?>.value(),
        returnValueForMissingStub: _i3.Future<_i4.UserCredential?>.value(),
      ) as _i3.Future<_i4.UserCredential?>);

  @override
  _i3.Future<_i4.UserCredential?> signInWithGoogle() => (super.noSuchMethod(
        Invocation.method(
          #signInWithGoogle,
          [],
        ),
        returnValue: _i3.Future<_i4.UserCredential?>.value(),
        returnValueForMissingStub: _i3.Future<_i4.UserCredential?>.value(),
      ) as _i3.Future<_i4.UserCredential?>);

  @override
  _i3.Future<void> sendPasswordResetEmail(String? email) => (super.noSuchMethod(
        Invocation.method(
          #sendPasswordResetEmail,
          [email],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i2.AppUser?> getAppUser(String? uid) => (super.noSuchMethod(
        Invocation.method(
          #getAppUser,
          [uid],
        ),
        returnValue: _i3.Future<_i2.AppUser?>.value(),
        returnValueForMissingStub: _i3.Future<_i2.AppUser?>.value(),
      ) as _i3.Future<_i2.AppUser?>);
}

/// A class which mocks [FirestoreService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirestoreService extends _i1.Mock implements _i5.FirestoreService {
  @override
  _i3.Stream<List<_i6.Hotel>> getHotelsStream() => (super.noSuchMethod(
        Invocation.method(
          #getHotelsStream,
          [],
        ),
        returnValue: _i3.Stream<List<_i6.Hotel>>.empty(),
        returnValueForMissingStub: _i3.Stream<List<_i6.Hotel>>.empty(),
      ) as _i3.Stream<List<_i6.Hotel>>);

  @override
  _i3.Future<List<_i6.Hotel>> getHotels() => (super.noSuchMethod(
        Invocation.method(
          #getHotels,
          [],
        ),
        returnValue: _i3.Future<List<_i6.Hotel>>.value(<_i6.Hotel>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i6.Hotel>>.value(<_i6.Hotel>[]),
      ) as _i3.Future<List<_i6.Hotel>>);

  @override
  _i3.Future<void> addHotel(_i6.Hotel? hotel) => (super.noSuchMethod(
        Invocation.method(
          #addHotel,
          [hotel],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateHotel(_i6.Hotel? hotel) => (super.noSuchMethod(
        Invocation.method(
          #updateHotel,
          [hotel],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteHotel(String? hotelId) => (super.noSuchMethod(
        Invocation.method(
          #deleteHotel,
          [hotelId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Stream<List<_i7.Favorite>> getFavoritesStream(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFavoritesStream,
          [userId],
        ),
        returnValue: _i3.Stream<List<_i7.Favorite>>.empty(),
        returnValueForMissingStub: _i3.Stream<List<_i7.Favorite>>.empty(),
      ) as _i3.Stream<List<_i7.Favorite>>);

  @override
  _i3.Future<List<_i7.Favorite>> getFavorites(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFavorites,
          [userId],
        ),
        returnValue: _i3.Future<List<_i7.Favorite>>.value(<_i7.Favorite>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i7.Favorite>>.value(<_i7.Favorite>[]),
      ) as _i3.Future<List<_i7.Favorite>>);

  @override
  _i3.Future<bool> isFavorite(
    String? userId,
    String? hotelId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #isFavorite,
          [
            userId,
            hotelId,
          ],
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<void> toggleFavorite(
    String? userId,
    String? hotelId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleFavorite,
          [
            userId,
            hotelId,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> removeFavorite(String? documentId) => (super.noSuchMethod(
        Invocation.method(
          #removeFavorite,
          [documentId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i8.User?> getUser(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #getUser,
          [userId],
        ),
        returnValue: _i3.Future<_i8.User?>.value(),
        returnValueForMissingStub: _i3.Future<_i8.User?>.value(),
      ) as _i3.Future<_i8.User?>);

  @override
  _i3.Future<void> createUser(_i8.User? user) => (super.noSuchMethod(
        Invocation.method(
          #createUser,
          [user],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateUser(_i8.User? user) => (super.noSuchMethod(
        Invocation.method(
          #updateUser,
          [user],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
